# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  right_elbow_joint:
    has_velocity_limits: true
    max_velocity: 37.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_hand_index_0_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_hand_index_1_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_hand_middle_0_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_hand_middle_1_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_hand_thumb_0_joint:
    has_velocity_limits: true
    max_velocity: 6.8570000000000002
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_hand_thumb_1_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_hand_thumb_2_joint:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 37.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_shoulder_roll_joint:
    has_velocity_limits: true
    max_velocity: 37.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 37.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 22.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 37.0
    has_acceleration_limits: false
    max_acceleration: 0.0
  right_wrist_yaw_joint:
    has_velocity_limits: true
    max_velocity: 22.0
    has_acceleration_limits: false
    max_acceleration: 0.0